const RESTAURANTS = [
  {
    id: "r001",
    name: "Essence",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "二星",
    cuisine: "歐陸當代料理（官方分類：European Contemporary）",
    chef: "Paul Froggatt（ROKI Collection 主廚總監）",
    priceNT: 5380,
    priceDisplay: "NZ$295–450／人（品嚐套餐）",
    priceVerified: true,
    within: false,
    reservation: "餐廳自行管理訂位，需直接聯繫餐廳",
    gmaps: "https://www.google.com/maps/search/?api=1&query=2%20Brunswick%20Street%2C%20Queenstown%2C%209300%EF%BC%88ROKI%20Collection%E5%85%A7%EF%BC%89",
    address: "2 Brunswick Street, Queenstown, 9300（ROKI Collection內）",
    signature: "生蠔、克雷鎮龍蝦、鴨肉、榲桲；侍酒師精選黑皮諾酒單",
    source: "guide.michelin.com/us/en/south-island/queenstown_2306160/restaurant/essence-1247217",
  },
  {
    id: "r002",
    name: "Ahi.",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，柴燒料理）",
    chef: "Ben Bayly",
    priceNT: 1620,
    priceDisplay: "三道式午／晚餐 NZ$89起；另有長套餐",
    priceVerified: true,
    within: true,
    reservation: "官方網站，可現場候位；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ahi.%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "卡瓦卡瓦酸種佐自製發酵奶油；帝馬圖庫生蠔、螯蝦",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/ahi",
  },
  {
    id: "r003",
    name: "Paris Butter",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，法式技法融合亞洲調味）",
    chef: "Nick Honeyman ＆ Zennon Wijlens",
    priceNT: 3010,
    priceDisplay: "季節套餐 NZ$145–185／人；侍酒搭配 +NZ$75–110",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位，需直接聯繫",
    gmaps: "https://www.google.com/maps/search/?api=1&query=166%20Jervois%20Road%2C%20Herne%20Bay%2C%20Auckland%2C%201011",
    address: "166 Jervois Road, Herne Bay, Auckland, 1011",
    signature: null,
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/paris-butter",
  },
  {
    id: "r004",
    name: "Tala",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "薩摩亞料理（官方分類：Samoan Cuisine，全球首個薩摩亞料理米其林星）",
    chef: "Henry ＆ Debby Onesemo",
    priceNT: 3470,
    priceDisplay: "「主廚之旅」14道 NZ$215／人；「故事之旅」NZ$165／人",
    priceVerified: true,
    within: true,
    reservation: "官方網站／電話，分三個場次；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=235%20Parnell%20Road%2C%20Parnell%2C%20Auckland%2C%201052",
    address: "235 Parnell Road, Parnell, Auckland, 1052",
    signature: "土窯烤春雞、椰漿麵包、太平洋海棗",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/tala",
  },
  {
    id: "r005",
    name: "Mudbrick",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，歐陸／日式／印度風味融合）",
    chef: "Mrinal Ghosal",
    priceNT: 3190,
    priceDisplay: "5道式套餐 NZ$175／人；另有3道式",
    priceVerified: true,
    within: true,
    reservation: "官方網站；電話 +64 9-372 9050",
    gmaps: "https://www.google.com/maps/search/?api=1&query=126%20Church%20Bay%20Road%2C%20Oneroa%2C%20Waiheke%20Island%2C%201971",
    address: "126 Church Bay Road, Oneroa, Waiheke Island, 1971",
    signature: "帝馬庫圖生蠔；琴通寧風味甜點",
    source: "guide.michelin.com/us/en/north-island/waiheke-island_2305319/restaurant/mudbrick",
  },
  {
    id: "r006",
    name: "The Estate（Tantalus Estate）",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，法式技法結合紐西蘭產地食材）",
    chef: "Axel Curtet-Latreille",
    priceNT: 3190,
    priceDisplay: "「信任主廚」5道式 NZ$175／人；另有3道式",
    priceVerified: true,
    within: true,
    reservation: "官方網站，務必訂位；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Tantalus%20Estate%2C%2070-72%20Onetangi%20Road%2C%20Waiheke%20Island%2C%201971",
    address: "Tantalus Estate, 70-72 Onetangi Road, Waiheke Island, 1971",
    signature: null,
    source: "guide.michelin.com/us/en/north-island/waiheke-island_2305319/restaurant/the-estate",
  },
  {
    id: "r007",
    name: "Amisfield",
    city: "皇后鎮",
    area: "雷斯湖",
    island: "南島",
    tier: "一星",
    cuisine: "創新料理（官方分類：Innovative，野生／採集食材為主）",
    chef: "Vaughan Mabee",
    priceNT: 7210,
    priceDisplay: "午餐套餐 NZ$395／人；晚餐12道式 NZ$440／人；至尊套餐 NZ$595／人",
    priceVerified: true,
    within: false,
    reservation: "線上Tock系統／email；2026年查詢時餐廳曾因整修暫時休業",
    gmaps: "https://www.google.com/maps/search/?api=1&query=10%20Arrowtown-Lake%20Hayes%20Road%2C%20Queenstown%2C%209371",
    address: "10 Arrowtown-Lake Hayes Road, Queenstown, 9371",
    signature: "野生黇鹿；莊園自產黑皮諾",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/amisfield；guide.michelin.com/nz/en/south-island/queenstown_2306160/restaurant/amisfield",
  },
  {
    id: "r008",
    name: "Rātā",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，中奧塔哥食材）",
    chef: "Josh Emett ＆ Fleur Caulton（主廚 Dan Matto）",
    priceNT: 1640,
    priceDisplay: "單點主菜 NZ$44–140／人（適量點餐可控制預算）",
    priceVerified: true,
    within: true,
    reservation: "官方網站；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Te%20Nuku%2C%2043%20Ballarat%20Street%2C%20Queenstown%2C%209348",
    address: "Te Nuku, 43 Ballarat Street, Queenstown, 9348",
    signature: null,
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/rata",
  },
  {
    id: "r009",
    name: "Sherwood",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，約九成食材自種／採集）",
    chef: "Chris Scott",
    priceNT: 1820,
    priceDisplay: "柴燒烤餅 NZ$12–30；3道式套餐 NZ$100／人",
    priceVerified: true,
    within: true,
    reservation: "餐廳官網直接聯繫；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=554%20Frankton%20Road%2C%20Queenstown%2C%209300",
    address: "554 Frankton Road, Queenstown, 9300",
    signature: "竹莢魚生食；柴燒烤餅",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/sherwood；guide.michelin.com/hk/en/south-island/queenstown_2306160/restaurant/sherwood",
  },
  {
    id: "r010",
    name: "Kika",
    city: "皇后鎮",
    area: "瓦納卡",
    island: "南島",
    tier: "一星",
    cuisine: "現代紐西蘭＋義式風味分享菜（官方英文分類未查證）",
    chef: "James Stapley",
    priceNT: 1820,
    priceDisplay: "「別問就吃」／「信任主廚」套餐約 NZ$100／人（含酒水搭配）",
    priceVerified: true,
    within: true,
    reservation: "官方網站線上訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Kika%20%E7%93%A6%E7%B4%8D%E5%8D%A1%20New%20Zealand%20restaurant",
    address: null,
    signature: "生牛肉塔塔佐溏心蛋；歐哈湖和牛牛小排",
    source: "未取得米其林官方Kika頁面核對結果",
  },
  {
    id: "r011",
    name: "Inati",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "歐陸當代料理（官方分類：European Contemporary）",
    chef: "Simon ＆ Lisa Levy",
    priceNT: 2740,
    priceDisplay: "「信任我們」6道式 NZ$129／人；8道式 NZ$165／人（另有含酒款套餐）",
    priceVerified: true,
    within: true,
    reservation: "官方網站／電話 +64 3-390 1580",
    gmaps: "https://www.google.com/maps/search/?api=1&query=48%20Hereford%20Street%2C%20Christchurch%20Central%20City%2C%20Christchurch%2C%208013",
    address: "48 Hereford Street, Christchurch Central City, Christchurch, 8013",
    signature: "「牛肉甜甜圈」（燉牛頰內餡）；14天熟成杜克香料鴨",
    source: "guide.michelin.com/en/south-island/christchurch_2307083/restaurant/inati；metropol.co.nz/christchurchs-michelin-guide",
  },
  {
    id: "r012",
    name: "Tussock Hill",
    city: "基督城",
    area: "卡什米爾",
    island: "南島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，僅供午餐時令分享菜）",
    chef: "Adam Harrison（官方頁面標示聲明人，原始資料未載主廚姓名）",
    priceNT: 1640,
    priceDisplay: "「精選午餐」NZ$90／人",
    priceVerified: true,
    within: true,
    reservation: "官方網站（僅供午餐）；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=210%20Huntsbury%20Avenue%2C%20Cashmere%2C%20Christchurch%2C%208022",
    address: "210 Huntsbury Avenue, Cashmere, Christchurch, 8022",
    signature: null,
    source: "guide.michelin.com/en/south-island/christchurch_2307083/restaurant/tussock-hill；metropol.co.nz/christchurchs-michelin-guide",
  },
  {
    id: "r013",
    name: "Apéro Food ＆ Wine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式(French)",
    chef: "未查證",
    priceNT: 350,
    priceDisplay: "單點制：小點NZ$9–14、大盤NZ$19–39、T骨牛排(2人份)NZ$145、甜點NZ$6–25（官網完整菜單）",
    priceVerified: true,
    within: true,
    reservation: "email：info@apero.co.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ap%C3%A9ro%20Food%20%EF%BC%86%20Wine%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "山羊乳酪可樂餅佐Kamahi蜂蜜；招牌香腸(依長度計價)",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/apero-food-wine；apero.co.nz；apero.co.nz/food",
  },
  {
    id: "r014",
    name: "Atelier",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式當代(French Contemporary)",
    chef: "未查證",
    priceNT: 1400,
    priceDisplay: "$$$(第一方資料)；信任主廚套餐NZ$75/人",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位；電話 +64 27-269 9306",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Atelier%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "自製鴨肝醬；多道式信任主廚套餐",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/atelier-1247986；atelierkrd.co.nz",
  },
  {
    id: "r015",
    name: "Bianca",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式(Italian)",
    chef: "未查證",
    priceNT: 930,
    priceDisplay: "主菜NZ$32–35；前菜/甜點另計；依Metro雜誌實測，人均約NZ$50–120視酒水",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bianca%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "手工義大利麵(官方文字未列明確招牌菜)",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/bianca-1248100；metromag.co.nz/food/food-restaurants/bianca-smart-business-casual-dining",
  },
  {
    id: "r016",
    name: "Bistro Saine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式(French)",
    chef: "未查證",
    priceNT: 1210,
    priceDisplay: "三道式套餐NZ$65／人（限定日）；單點前菜NZ$12–36、主菜NZ$26–95",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-610 8404",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bistro%20Saine%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "絲滑雞肝凍；茴香醬羊排佐法式馬鈴薯球",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/bistro-saine；bistrosaine.co.nz/our-menu",
  },
  {
    id: "r017",
    name: "Boda",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "韓式當代(Korean Contemporary，非原始資料泰式)",
    chef: "未查證",
    priceNT: 1030,
    priceDisplay: "兩道式套餐NZ$55／人；週末Bottomless Brunch NZ$69／人；Chef Series活動NZ$59–160／人",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Boda%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "瑞可塔起司麵疙瘩年糕(韓義融合)",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/boda；boda.restaurant",
  },
  {
    id: "r018",
    name: "Cazador",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "紐西蘭料理(New Zealand)",
    chef: "未查證",
    priceNT: 1810,
    priceDisplay: "NZ$99／人套餐（Cazador「盛宴」）",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Cazador%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "盛宴套餐；野味料理、自製醃肉拼盤",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/cazador",
  },
  {
    id: "r019",
    name: "Gemmayze Street",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "黎巴嫩(Lebanese)",
    chef: "未查證",
    priceNT: 1370,
    priceDisplay: "主餐 NZ$40，套餐 NZ$65–110",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位；營業時間週二至週六18:00-22:00",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Gemmayze%20Street%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "自製皮塔餅；鷹嘴豆泥；多汁雞腿肉",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/gemmayze-street",
  },
  {
    id: "r020",
    name: "Goat",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "印度料理(Indian，非原始資料小盤料理)",
    chef: "Sid Chopra",
    priceNT: 1590,
    priceDisplay: "全菜單套餐NZ$85／人（依Reddit在地食客實測討論）",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位；電話+64 9-377 7414",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Goat%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "招牌菜The Goat(比哈爾邦風味慢燉羊肉)；印度奶茶提拉米蘇",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/goat-1246393；reddit.com/r/aucklandeats",
  },
  {
    id: "r021",
    name: "Milenta",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "拉丁美洲料理(Latin American)",
    chef: "未查證(哥倫比亞籍)",
    priceNT: 1400,
    priceDisplay: "四道式午／晚套餐NZ$75／人；單點NZ$5（生蠔）至NZ$75（55天熟成肋眼）",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位；營業時間週三至週六",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Milenta%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "生醃海鮮佐辣醬與地瓜片",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/milenta；businessdesk.co.nz；heartofthecity.co.nz",
  },
  {
    id: "r022",
    name: "Osteria Uno",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式(Italian)",
    chef: "未查證",
    priceNT: 490,
    priceDisplay: "義大利麵NZ$26–30、前菜NZ$10–22；週六長午餐套餐NZ$59／人（含氣泡酒）",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Osteria%20Uno%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "手工蟹肉餃；自製巴薩米克奶油佛卡夏",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/osteria-uno；nzherald.co.nz；osteriauno.co.nz/longlunch",
  },
  {
    id: "r023",
    name: "Parro",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "地中海料理(Mediterranean，主廚西班牙受訓/巴西籍團隊)",
    chef: "未查證",
    priceNT: 560,
    priceDisplay: "主菜NZ$30–40；前菜NZ$10–34（依NZ Herald實測評論）",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位(極熱門，須提前訂位)",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Parro%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "炭烤BBQ薄餅佐辣蝦；提拉米蘇",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/parro；nzherald.co.nz",
  },
  {
    id: "r024",
    name: "Pasta ＆ Cuore",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式手工麵食(Italian)",
    chef: "未查證",
    priceNT: 520,
    priceDisplay: "義大利麵NZ$28–36；前菜NZ$18–29.50；甜點NZ$12.50–16.50",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Pasta%20%EF%BC%86%20Cuore%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "手工麵疙瘩；每日現做麵包",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/pasta-cuore；nzherald.co.nz；pastaecuore.co.nz/menu",
  },
  {
    id: "r025",
    name: "Tempero",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "泛拉丁美洲(Pan-Latin)",
    chef: "未查證",
    priceNT: 1120,
    priceDisplay: "Feijoada Night套餐NZ$60／人（單人）；分享盤NZ$15–80（依Cuisine雜誌）",
    priceVerified: true,
    within: true,
    reservation: "email訂位可透過temperoakl.com網站表單",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Tempero%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "精緻拉丁美洲小酒館菜色，2023年開業",
    source: "guide.michelin.com/us/en/north-island/auckland_2302926/restaurant/tempero-1248090；temperoakl.com；cuisine.co.nz/tempero",
  },
  {
    id: "r026",
    name: "A'mano",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "義式(Italian，手工現做義大利麵/佛卡夏/甜點)",
    chef: "未查證",
    priceNT: 500,
    priceDisplay: "主菜NZ$27–36（義大利麵／燉飯類，官網現行菜單）",
    priceVerified: true,
    within: true,
    reservation: "電話 +64 3-925 9986",
    gmaps: "https://www.google.com/maps/search/?api=1&query=A%27mano%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "布魯斯凱塔；緩燉牛頰肉千層麵；輕盈提拉米蘇",
    source: "guide.michelin.com/us/en/south-island/christchurch_2307083/restaurant/a-mano-1247933；amanocucina.co.nz/collections/all-menu；firsttable.co.nz",
  },
  {
    id: "r027",
    name: "Earl",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "歐式小酒館(European，2018年開業)",
    chef: "未查證",
    priceNT: 1480,
    priceDisplay: "主廚精選套餐NZ$79／人（不含酒；含酒單搭配NZ$125／人）；週二Pasta Night固定NZ$28／人",
    priceVerified: true,
    within: true,
    reservation: "官網訂位頁面earl.co.nz（無獨立線上訂位系統，僅電話）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Earl%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "鹿肉；寬扁麵；巧克力恩特梅茶點；週二Pasta Night",
    source: "guide.michelin.com/tw/en/south-island/christchurch_2307083/restaurant/earl；metropol.co.nz；earl.co.nz/dinner-menu",
  },
  {
    id: "r028",
    name: "Fire and Slice",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "披薩專門店(Pizza)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Fire%20and%20Slice%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "手工拉製薄脆披薩，柴燒窯烤",
    source: "guide.michelin.com/nz/en/south-island/christchurch_2307083/restaurant/fire-and-slice",
  },
  {
    id: "r029",
    name: "Gatherings",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "時令有機料理",
    chef: "未查證",
    priceNT: 1120,
    priceDisplay: "晚餐五道式套餐NZ$60／人（不含酒；可加酒單搭配至NZ$100／人）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Gatherings%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "峽灣鹿肉；三道式套餐；僅20席",
    source: "metropol.co.nz/christchurchs-michelin-guide；stuff.co.nz；cuisine.co.nz/gatherings",
  },
  {
    id: "r030",
    name: "Londo",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "當代紐西蘭料理(Contemporary/New Zealand)",
    chef: "Robert Fairs(獲2026 MICHELIN Young Chef Award)",
    priceNT: 450,
    priceDisplay: "主菜／分享盤價格帶約NZ$24–35（依Christchurch NZ官方美食網站）",
    priceVerified: true,
    within: true,
    reservation: "電話 +64 27-340 8385",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Londo%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "55天熟成坎特伯里草飼牛肉塔塔",
    source: "guide.michelin.com/en/south-island/christchurch_2307083/restaurant/londo；christchurchnz.com/visit/eat-and-drink/food-guide/londo",
  },
  {
    id: "r031",
    name: "Odeon",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "安達魯西亞地中海/中東料理",
    chef: "未查證",
    priceNT: 1660,
    priceDisplay: "「Just Feed Me」套餐NZ$89／人（不含酒）；單點招牌大份享用菜NZ$65",
    priceVerified: true,
    within: true,
    reservation: "電話 +64 22-420 1378",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Odeon%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "Akaroa鮭魚；Lumina羊肉；Just Feed Me主廚精選套餐",
    source: "guide.michelin.com/nz/en/south-island/christchurch_2307083/restaurant/odeon；odeon.co.nz/dinner-menu",
  },
  {
    id: "r032",
    name: "Roca",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "地中海料理",
    chef: "未查證",
    priceNT: 1870,
    priceDisplay: "兩人用餐（含酒）實測約NZ$230，即人均約NZ$100–115（依Tripadvisor實測評論）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Roca%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/south-island/christchurch_2307083/restaurant/roca；tripadvisor.com（用戶實測帳單）",
  },
  {
    id: "r033",
    name: "Soul Quarter",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "南方料理風格(Southern-inspired)",
    chef: "未查證",
    priceNT: 820,
    priceDisplay: "巨無霸明蝦約NZ$3／隻；炭烤羊肉盤約NZ$45",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Soul%20Quarter%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "metropol.co.nz/christchurchs-michelin-guide",
  },
  {
    id: "r034",
    name: "The Athens Yacht Club",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "希臘料理(Greek)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Athens%20Yacht%20Club%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "解構式慕沙卡；招牌AYC火燄乳酪開胃菜",
    source: "metropol.co.nz/christchurchs-michelin-guide",
  },
  {
    id: "r035",
    name: "The Monday Room",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "歐式家庭式分享餐(European)",
    chef: "未查證",
    priceNT: 1400,
    priceDisplay: "主廚套餐四道NZ$75／人（食物）；單點主菜NZ$37–112；Tripadvisor估算含酒人均約NZ$140–220",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Monday%20Room%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "主廚精選套餐(banquet menu)",
    source: "metropol.co.nz/christchurchs-michelin-guide；cuisine.co.nz/the-monday-room；tripadvisor.com",
  },
  {
    id: "r036",
    name: "Aosta",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "北義料理(Northern-Italian)",
    chef: "Andrea Cattalini(主理主廚)/擁有者Ben Bayly",
    priceNT: 2240,
    priceDisplay: "4道式套餐NZ$120/人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-442 0131 或 +64 29-020 0019",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Aosta%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "提拉米蘇佐Baileys、杏仁香甜酒與鹽味焦糖；珍珠小牛肉Tonnato",
    source: "guide.michelin.com/nz/en/south-island/arrowtown_2306844/restaurant/aosta；cuisine.co.nz",
  },
  {
    id: "r037",
    name: "Bombay Palace",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "印度料理(Indian)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "電話 +64 3-428 4201",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bombay%20Palace%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/south-island/wanaka_2306683/restaurant/bombay-palace-wanaka；bombaypalace.co.nz",
  },
  {
    id: "r038",
    name: "Francesca",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "義式(Italian)",
    chef: "Lucas(主廚)",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "電話 +64 3-443 5599",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Francesca%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "柴燒窯烤義式料理",
    source: "guide.michelin.com/en/south-island/wanaka_2306683/restaurant/francesca；francescawanaka.co.nz",
  },
  {
    id: "r039",
    name: "Muttonbird",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "紐西蘭料理(帶亞洲融合，目前暫時停業)",
    chef: "未查證",
    priceNT: 1490,
    priceDisplay: "主廚精選9道式套餐約NZ$80/人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-428 4223",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Muttonbird%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "耶路撒冷朝鮮薊、雞肝凍",
    source: "guide.michelin.com/en/south-island/wanaka_2306683/restaurant/muttonbird",
  },
  {
    id: "r040",
    name: "Paloma Taqueria",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "墨西哥料理(Mexican)",
    chef: "James Stapley",
    priceNT: 820,
    priceDisplay: "任選套餐約NZ$49／人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-443 1288",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Paloma%20Taqueria%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "現做玉米餅塔可；辣炒蘑菇捲餅佐番茄莎莎與新鮮乳酪",
    source: "guide.michelin.com/en/south-island/wanaka_2306683/restaurant/paloma-taqueria；wanaka.co.nz",
  },
  {
    id: "r041",
    name: "Sundays",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "皇后鎮，當代料理",
    chef: "未查證",
    priceNT: 820,
    priceDisplay: "柴燒披薩NZ$30–34、經典起司義大利麵NZ$27",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Sundays%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/sundays-1241047",
  },
  {
    id: "r042",
    name: "The Cow",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "皇后鎮，披薩與起司鍋",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Cow%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/the-cow-queenstown",
  },
  {
    id: "r043",
    name: "Treehouse",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "酒吧/分享小盤(Bar/Wine Bar)",
    chef: "未查證",
    priceNT: 920,
    priceDisplay: "主廚精選套餐約NZ$49/人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-443 7344",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Treehouse%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "Otago內格羅尼；鮑魚可樂餅",
    source: "guide.michelin.com/gb/en/south-island/wanaka_2306683/restaurant/treehouse；treehousewanaka.nz",
  },
  {
    id: "r044",
    name: "The French Café",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "紐西蘭料理",
    chef: "Sid Sahrawat/Chand Sahrawat(侍酒師Matthew Aitchison獲2026 Sommelier Award)",
    priceNT: 2830,
    priceDisplay: "食物套餐 NZ$155–190／人（不含酒款）；含酒款可達NZ$305",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=210%20Symonds%20Street%2C%20Eden%20Terrace%2C%20Auckland%2C%201011",
    address: "210 Symonds Street, Eden Terrace, Auckland, 1011",
    signature: "紐西蘭2026米其林侍酒師大獎得主餐廳（主理人Matthew Aitchison）；主廚Sid與Chand Sahrawat",
    source: "guide.michelin.com官方新聞稿-2026 MICHELIN Guide New Zealand Restaurant Selection",
  },
  {
    id: "r045",
    name: "Onslow",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "未查證具體官方分類(第三方稱紐西蘭當代料理)",
    chef: "Josh Emett",
    priceNT: 710,
    priceDisplay: "主菜NZ$38-98",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-930 9123；官網onslow.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Onslow%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "未查證具體招牌菜",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/onslow-1241070；cuisine.co.nz",
  },
  {
    id: "r046",
    name: "Cassia",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "印度料理(Indian，目前暫時停業)",
    chef: "Sid Sahrawat",
    priceNT: 1820,
    priceDisplay: "蔬食套餐 NZ$175／人；單點約NZ$100／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Cassia%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "2026年搬遷至市中心新址",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/cassia-1244159",
  },
  {
    id: "r047",
    name: "Metita",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "薩摩亞料理(Samoan Cuisine)",
    chef: "Michael Meredith",
    priceNT: 640,
    priceDisplay: "單點主菜 NZ$30–40",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Metita%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "Panikeke薩摩亞炸甜甜圈；柴燒鯛魚或鴨胸；酥脆豬腳佐sapa sui",
    source: "guide.michelin.com/hr/en/north-island/auckland_2302926/restaurant/metita",
  },
  {
    id: "r048",
    name: "Kol",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "未查證具體官方分類",
    chef: "Sahrawat家族",
    priceNT: 730,
    priceDisplay: "單點 NZ$20–42；主廚精選套餐約NZ$95",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Kol%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/kol-1246386",
  },
  {
    id: "r049",
    name: "Origine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代法式小酒館(Modern French Bistro)",
    chef: "Ben Bayly",
    priceNT: 670,
    priceDisplay: "主菜NZ$36-110",
    priceVerified: true,
    within: true,
    reservation: "電話+64 27-674 4463；官網origine.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Origine%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "傳統法式牛肉丁佐薯條(Steak hache)",
    source: "cuisine.co.nz；nzherald.co.nz",
  },
  {
    id: "r050",
    name: "Mr Morris",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "國際/紐西蘭融合(官方未列具體分類)",
    chef: "Michael Meredith(主理)/Zane Neustroski(總廚)",
    priceNT: 750,
    priceDisplay: "主菜NZ$40-49；體驗套餐約NZ$200含酒單",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-869 5522；eat@mrmorris.nz；mrmorris.nz/reservations",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Mr%20Morris%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "抱子甘藍佐nduja辣香腸與白洋蔥；南瓜義式餃",
    source: "guide.michelin.com/nz/en/north-island/auckland_2302926/restaurant/mr-morris；cuisine.co.nz",
  },
  {
    id: "r051",
    name: "Kingi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "未查證(第三方多稱海鮮料理)",
    chef: "Tom Hishon",
    priceNT: 770,
    priceDisplay: "單點主菜 NZ$38–46",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Kingi%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/jp/ja/north-island/auckland_2302926/restaurant/kingi",
  },
  {
    id: "r052",
    name: "Ki Māha",
    city: "奧克蘭",
    area: "懷赫科島（Waiheke Island，米其林官網獨立列為此地區）",
    island: "北島",
    tier: "精選",
    cuisine: "懷希基島，紐西蘭／國際料理",
    chef: "Vicky Shah",
    priceNT: null,
    priceDisplay: "未查證（原始資料僅記錄「單點＋3道式套餐」，無確切金額）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ki%20M%C4%81ha%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r053",
    name: "Gilt（Gilt Brasserie）",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐式(European)",
    chef: "Josh ＆ Helen Emett",
    priceNT: 770,
    priceDisplay: "單點主菜 NZ$38–46",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Gilt%EF%BC%88Gilt%20Brasserie%EF%BC%89%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/jp/en/north-island/auckland_2302926/restaurant/gilt",
  },
  {
    id: "r054",
    name: "Esther",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "地中海料理(Mediterranean Cuisine)",
    chef: "Sean Connolly",
    priceNT: 1130,
    priceDisplay: "戲前2道式 NZ$59；套餐約NZ$65",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Esther%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/us/en/north-island/auckland_2302926/restaurant/esther",
  },
  {
    id: "r055",
    name: "Baduzzi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義美融合(Italian-American)",
    chef: "Michael Dearth",
    priceNT: 380,
    priceDisplay: "單盤 NZ$14–28",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Baduzzi%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/us/en/north-island/auckland_2302926/restaurant/baduzzi",
  },
  {
    id: "r056",
    name: "Jervois Steak House",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "牛排館(Steakhouse)",
    chef: "未查證主廚；總經理Matteo Mannoni",
    priceNT: 3380,
    priceDisplay: "實測含餐酒總帳單NZ$362／2人（約NZ$181／人，依NZ Herald）；單點主菜牛排NZ$49–85、前菜NZ$26–30",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-376 2049",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Jervois%20Steak%20House%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "皇后鎮亦有分店",
    source: "guide.michelin.com/us/en/north-island/auckland_2302926/restaurant/jervois-steak-house-1248037；tripadvisor；jervoissteakhouse.co.nz/menu；nzherald.co.nz",
  },
  {
    id: "r057",
    name: "Sails",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "海鮮料理(Seafood)",
    chef: "未查證",
    priceNT: 2800,
    priceDisplay: "6道式套餐約NZ$150/人(早期評論，須以官網最新為準)",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-378 9890",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Sails%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "碼頭景觀，品嚐套餐可能接近預算上限",
    source: "guide.michelin.com/de/de/north-island/auckland_2302926/restaurant/sails",
  },
  {
    id: "r058",
    name: "Otto",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式(Italian)",
    chef: "未查證",
    priceNT: 510,
    priceDisplay: "單點多在NZ$28以內",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-394 1555；bookings@otto-krd.nz；otto-krd.nz/bookings",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Otto%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "手工義大利麵；雞尾酒吧",
    source: "guide.michelin.com/nz/en/north-island/auckland_2302926/restaurant/otto-1244161",
  },
  {
    id: "r059",
    name: "Lillius",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸料理",
    chef: "Fraser McCarthy",
    priceNT: 1280,
    priceDisplay: "3道式套餐 NZ$70／人；另有5／8道式品嚐套餐",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Lillius%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r060",
    name: "Ada",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "西班牙料理(Spanish)",
    chef: "Kia Kanuta",
    priceNT: 1620,
    priceDisplay: "「餵飽我」套餐 NZ$89／人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 21-090 90101；Bookings@adarestaurant.co.nz；adarestaurant.co.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ada%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/ada-1248048",
  },
  {
    id: "r061",
    name: "Advieh",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "中東波斯地中海融合(Middle Eastern/Persian-Mediterranean)",
    chef: "Gareth Stewart",
    priceNT: 1950,
    priceDisplay: "宴席套餐 NZ$89或NZ$125／人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-304 0040；advieh.restaurant@ihg.com",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Advieh%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "全日供餐，中東香料料理",
    source: "guide.michelin.com/tw/en/north-island/auckland_2302926/restaurant/advieh",
  },
  {
    id: "r062",
    name: "Alma",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "西班牙安達魯西亞風格(Spanish/Andalusian)",
    chef: "未查證",
    priceNT: 1730,
    priceDisplay: "團體套餐 NZ$95／人；單點NZ$6–120（龍蝦類單點可能超出預算）",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-242 1570；alma.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Alma%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "柴火慢燉羊肉佐香草香菜醬；鯷魚；牛舌",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/alma-1244170；broadsheet.com.au",
  },
  {
    id: "r063",
    name: "Bar Magda",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代菲律賓料理(Filipino)",
    chef: "Carlo Buenaventura",
    priceNT: 340,
    priceDisplay: "主菜NZ$18-28；分享套餐約NZ$55/人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 21-127 9377；barmagda.co.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bar%20Magda%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "醃漬大頭菜佐椰奶番紅花醬；牛頰肉佐青花菜泥與費約果醬",
    source: "cuisine.co.nz；nzherald.co.nz",
  },
  {
    id: "r064",
    name: "Bossi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式(Italian)",
    chef: "Shaun Dowling",
    priceNT: 600,
    priceDisplay: "單點主菜 NZ$26–40",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bossi%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/bossi",
  },
  {
    id: "r065",
    name: "East",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "未查證(官網頁面截斷)",
    chef: "未查證",
    priceNT: 1550,
    priceDisplay: "「信任主廚」套餐 NZ$85／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=East%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/us/en/north-island/auckland_2302926/restaurant/east-1246385",
  },
  {
    id: "r066",
    name: "Hello Beasty",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代亞洲融合(Asian Contemporary)",
    chef: "Stuart Rogan",
    priceNT: 690,
    priceDisplay: "主菜NZ$37-40",
    priceVerified: true,
    within: true,
    reservation: "電話+64 21-554 496；emma@hellobeasty.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Hello%20Beasty%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "泛亞洲風味多元菜色，濱海景觀",
    source: "guide.michelin.com/nz/en/north-island/auckland_2302926/restaurant/hello-beasty；cuisine.co.nz",
  },
  {
    id: "r067",
    name: "Morell",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "未查證(第三方稱時尚現代小酒館)",
    chef: "未查證",
    priceNT: 450,
    priceDisplay: "義大利麵／主菜NZ$24–36；前菜NZ$16–19；套餐午餐(含酒)NZ$25／人",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-600 3259",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Morell%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/us/en/north-island/auckland_2302926/restaurant/morell；nzherald.co.nz；firsttable.co.nz/auckland/remuera/morell",
  },
  {
    id: "r068",
    name: "One Tree Grill",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "牛排館/歐式/紐西蘭料理",
    chef: "未查證",
    priceNT: 1060,
    priceDisplay: "單點主菜 NZ$27–58；6道式品嚐套餐可能超出預算",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-909 7215",
    gmaps: "https://www.google.com/maps/search/?api=1&query=One%20Tree%20Grill%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "奧克蘭老字號名店",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/one-tree-grill；onetreegrill.co.nz",
  },
  {
    id: "r069",
    name: "Ragtag",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "墨西哥風味(Mexican-inspired，100%非正宗自我定位)",
    chef: "Dan Freeman",
    priceNT: 520,
    priceDisplay: "主菜NZ$28–37；塔可NZ$15–21（依NZ Herald實測菜單）",
    priceVerified: true,
    within: true,
    reservation: "電話+64 21-409 879；hello@ragtagnz.com",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ragtag%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "脆皮手撕鴨佐鴨油玉米餅",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/ragtag；ragtagnz.com；nzherald.co.nz",
  },
  {
    id: "r070",
    name: "Rodd ＆ Gunn The Lodge",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "紐西蘭料理(服飾品牌跨界餐廳)",
    chef: "Matt Lambert",
    priceNT: 820,
    priceDisplay: "前菜 NZ$15–29；主菜 NZ$25–45（牛排單點可達NZ$85）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Rodd%20%EF%BC%86%20Gunn%20The%20Lodge%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "生醃黃尾魚；和牛韃靼；生蠔；瓦皮提鹿肉；海鮮派",
    source: "guide.michelin.com/us/en/south-island/queenstown_2306160/restaurant/rodd-gunn-the-lodge-1241051；wanderlog.com",
  },
  {
    id: "r071",
    name: "1947 Eatery",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "印度料理(Indian)",
    chef: "Jaspal Singh",
    priceNT: 1300,
    priceDisplay: "六人共同消費約NZ$416含酒水，換算每人約NZ$69（依NZ Herald實測，非官方單人定價）",
    priceVerified: true,
    within: true,
    reservation: "電話+64 9-377 0033",
    gmaps: "https://www.google.com/maps/search/?api=1&query=1947%20Eatery%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "Dum Biryani；街頭小吃風格印度料理",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/1947-eatery；nzherald.co.nz",
  },
  {
    id: "r072",
    name: "Bessie",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "牛排館/歐式(Steakhouse/European，乾式熟成牛肉專門)",
    chef: "未查證",
    priceNT: 800,
    priceDisplay: "前菜NZ$14–29；主菜NZ$43–49；分享熟成牛排NZ$100以上；配菜NZ$17–19（依Belly Rumbles實地用餐紀錄）",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-595 2799",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bessie%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "乾式熟成肋眼；鴨油炸馬鈴薯可樂餅；巧克力慕斯蛋糕",
    source: "guide.michelin.com/sg/zh_CN/south-island/christchurch_2307083/restaurant/bessie；tripadvisor；bellyrumbles.com/bessie-restaurant-christchurch",
  },
  {
    id: "r073",
    name: "Cellar Door",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "酒吧型態創意佐酒料理(Wine Bar)",
    chef: "Anna Victoria",
    priceNT: 520,
    priceDisplay: "主菜NZ$28-34",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-925 8497",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Cellar%20Door%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "乳酪火鍋(cheese fondue)；美麗諾羊肉燉肉醬",
    source: "metropol.co.nz；cuisine.co.nz",
  },
  {
    id: "r074",
    name: "Hugo",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "法式(French，仿巴黎現代小酒館)",
    chef: "未查證",
    priceNT: 640,
    priceDisplay: "主菜約NZ$34-46(依實測約NZ$160/人含酒水)",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-374 5200",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Hugo%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "鴨肉油封；肝醬(liver parfait)；韃靼牛肉；蘋果反烤塔",
    source: "guide.michelin.com/us/en/south-island/christchurch_2307083/restaurant/hugo-1247929；tripadvisor",
  },
  {
    id: "r075",
    name: "Miro",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "歐式/紐西蘭料理(河畔1930年代歷史建築)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "$$（官方MICHELIN符號，未提供確切NZD金額，無法換算NT$）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-925 9909",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Miro%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "火爐邊燉羊肉派；招牌凱薩沙拉；人氣早午餐",
    source: "metropol.co.nz；guide.michelin.com/hk/en/south-island/christchurch_2307083/restaurant/miro-1241080",
  },
  {
    id: "r076",
    name: "Arc",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Arc%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "guide.michelin.com/en/south-island/wanaka_2306683/restaurant/arc",
  },
  {
    id: "r077",
    name: "Bianca by Giovi",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "義式/披薩(Italian/Pizza，Giovi Fine Food集團第三間分店)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "母公司電話03-442 2900(直接電話未查證)",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bianca%20by%20Giovi%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "手工現做義大利麵；瑪格麗特披薩；提拉米蘇",
    source: "tripadvisor；giovifinefood.co.nz",
  },
  {
    id: "r078",
    name: "Billy's",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-974 4091",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Billy%27s%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "與The Woolshed同園區(Ayrburn)，2026年新開幕",
    source: "guide.michelin.com/ca/fr/south-island/arrowtown_2306844/restaurant/billy-s",
  },
  {
    id: "r079",
    name: "Botswana Butchery",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "牛排館(Steakhouse，歷史建築Archer's Cottage)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "精緻肉類料理，高級部位可能超出NT$5,000",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-442 6994；queenstown@botswanabutchery.co.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Botswana%20Butchery%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "瓦卡蒂普湖景觀座位；牛排館經典菜色",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/botswana-butchery；botswanabutchery.nz",
  },
  {
    id: "r080",
    name: "Jervois Steak House",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "牛排館(Steakhouse)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "高級牛排單點可能超出預算",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Jervois%20Steak%20House%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: "metropol.co.nz官方名單確認在列",
  },
  {
    id: "r081",
    name: "Millhouse",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-441 7005；millhouse@millbrook.co.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Millhouse%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "度假村內精緻餐飲，週三至週日17:30起營業",
    source: "guide.michelin.com/us/en/south-island/arrowtown_2306844/restaurant/millhouse；millbrook.co.nz",
  },
  {
    id: "r082",
    name: "Nest",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代紐西蘭/地中海風格",
    chef: "未查證",
    priceNT: 560,
    priceDisplay: "3道式套餐(可加購約NZ$30/人升級套餐)",
    priceVerified: true,
    within: true,
    reservation: "電話+64 3-901 0284",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Nest%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "高處露天用餐，可俯瞰瓦卡蒂普湖景",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/nest-1241049；tripadvisor",
  },
  {
    id: "r083",
    name: "Rodd ＆ Gunn The Lodge",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "紐西蘭料理(服飾品牌跨界餐廳)",
    chef: "未查證(侍酒大師Cameron Douglas策劃酒單)",
    priceNT: null,
    priceDisplay: "未查證（同品牌奧克蘭分店主菜NZ$25–45，皇后鎮分店價位可能相近但未逐一確認）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-442 9426",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Rodd%20%EF%BC%86%20Gunn%20The%20Lodge%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "生醃黃尾魚；和牛韃靼；生蠔；瓦皮提鹿肉；海鮮派",
    source: "guide.michelin.com/us/en/south-island/queenstown_2306160/restaurant/rodd-gunn-the-lodge-1241051；wanderlog.com",
  },
  {
    id: "r084",
    name: "Soda",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "地中海融合(第三方稱)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-442 5288",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Soda%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "煙燻蒜泥烤章魚佐開心果調味料(gremolata)",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/soda",
  },
  {
    id: "r085",
    name: "The Dining Room",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "未查證(位於Rosewood Matakauri頂級度假村內)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "精緻套餐，可能接近或超出預算上限",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Dining%20Room%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "度假村內高級餐廳",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/the-dining-room-1241050",
  },
  {
    id: "r086",
    name: "The Woolshed",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "紐西蘭/國際料理(修復穀倉建築)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-974 4091",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Woolshed%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "招牌羊肩肉；菠菜瑞可塔義式方餃；爐火邊用餐",
    source: "guide.michelin.com/en/south-island/arrowtown_2306844/restaurant/the-woolshed；tripadvisor",
  },
  {
    id: "r087",
    name: "Toast ＆ Oak",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "時尚歐陸菜(European Contemporary)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "$$$（官方MICHELIN符號，未提供確切NZD金額，無法換算NT$）",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-442 8627",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Toast%20%EF%BC%86%20Oak%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "酒吧型態小盤料理；橡木風味餐酒搭配",
    source: "guide.michelin.com/nz/en/south-island/queenstown_2306160/restaurant/toast-oak",
  },
  {
    id: "r088",
    name: "True South Dining Room",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代紐西蘭料理(Modern New Zealand)",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "精緻套餐，可能接近或超出預算上限",
    priceVerified: false,
    within: null,
    reservation: "電話+64 3-450 1100；restaurant@therees.co.nz",
    gmaps: "https://www.google.com/maps/search/?api=1&query=True%20South%20Dining%20Room%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: "湖畔景觀餐廳，位於The Rees飯店內",
    source: "restaurantsforkings.com；facebook.com/truesouthdining",
  },
];
