const RESTAURANTS = [
  {
    id: "r001",
    name: "Essence",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "二星",
    cuisine: "歐陸當代料理（官方分類：European Contemporary）",
    chef: "Paul Froggatt（ROKI Collection 主廚總監）",
    priceNT: 5380,
    priceDisplay: "NZ$295–450／人（品嚐套餐）",
    priceVerified: true,
    within: false,
    reservation: "餐廳自行管理訂位，需直接聯繫餐廳",
    gmaps: "https://www.google.com/maps/search/?api=1&query=2%20Brunswick%20Street%2C%20Queenstown%2C%209300%EF%BC%88ROKI%20Collection%E5%85%A7%EF%BC%89",
    address: "2 Brunswick Street, Queenstown, 9300（ROKI Collection內）",
    signature: "生蠔、克雷鎮龍蝦、鴨肉、榲桲；侍酒師精選黑皮諾酒單",
    source: "guide.michelin.com/us/en/south-island/queenstown_2306160/restaurant/essence-1247217",
  },
  {
    id: "r002",
    name: "Ahi.",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，柴燒料理）",
    chef: "Ben Bayly",
    priceNT: 1620,
    priceDisplay: "三道式午／晚餐 NZ$89起；另有長套餐",
    priceVerified: true,
    within: true,
    reservation: "官方網站，可現場候位；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ahi.%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "卡瓦卡瓦酸種佐自製發酵奶油；帝馬圖庫生蠔、螯蝦",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/ahi",
  },
  {
    id: "r003",
    name: "Paris Butter",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，法式技法融合亞洲調味）",
    chef: "Nick Honeyman ＆ Zennon Wijlens",
    priceNT: 3010,
    priceDisplay: "季節套餐 NZ$145–185／人；侍酒搭配 +NZ$75–110",
    priceVerified: true,
    within: true,
    reservation: "餐廳自行管理訂位，需直接聯繫",
    gmaps: "https://www.google.com/maps/search/?api=1&query=166%20Jervois%20Road%2C%20Herne%20Bay%2C%20Auckland%2C%201011",
    address: "166 Jervois Road, Herne Bay, Auckland, 1011",
    signature: null,
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/paris-butter",
  },
  {
    id: "r004",
    name: "Tala",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "薩摩亞料理（官方分類：Samoan Cuisine，全球首個薩摩亞料理米其林星）",
    chef: "Henry ＆ Debby Onesemo",
    priceNT: 3470,
    priceDisplay: "「主廚之旅」14道 NZ$215／人；「故事之旅」NZ$165／人",
    priceVerified: true,
    within: true,
    reservation: "官方網站／電話，分三個場次；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=235%20Parnell%20Road%2C%20Parnell%2C%20Auckland%2C%201052",
    address: "235 Parnell Road, Parnell, Auckland, 1052",
    signature: "土窯烤春雞、椰漿麵包、太平洋海棗",
    source: "guide.michelin.com/en/north-island/auckland_2302926/restaurant/tala",
  },
  {
    id: "r005",
    name: "Mudbrick",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，歐陸／日式／印度風味融合）",
    chef: "Mrinal Ghosal",
    priceNT: 3190,
    priceDisplay: "5道式套餐 NZ$175／人；另有3道式",
    priceVerified: true,
    within: true,
    reservation: "官方網站；電話 +64 9-372 9050",
    gmaps: "https://www.google.com/maps/search/?api=1&query=126%20Church%20Bay%20Road%2C%20Oneroa%2C%20Waiheke%20Island%2C%201971",
    address: "126 Church Bay Road, Oneroa, Waiheke Island, 1971",
    signature: "帝馬庫圖生蠔；琴通寧風味甜點",
    source: "guide.michelin.com/us/en/north-island/waiheke-island_2305319/restaurant/mudbrick",
  },
  {
    id: "r006",
    name: "The Estate（Tantalus Estate）",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，法式技法結合紐西蘭產地食材）",
    chef: "Axel Curtet-Latreille",
    priceNT: 3190,
    priceDisplay: "「信任主廚」5道式 NZ$175／人；另有3道式",
    priceVerified: true,
    within: true,
    reservation: "官方網站，務必訂位；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Tantalus%20Estate%2C%2070-72%20Onetangi%20Road%2C%20Waiheke%20Island%2C%201971",
    address: "Tantalus Estate, 70-72 Onetangi Road, Waiheke Island, 1971",
    signature: null,
    source: "guide.michelin.com/us/en/north-island/waiheke-island_2305319/restaurant/the-estate",
  },
  {
    id: "r007",
    name: "Amisfield",
    city: "皇后鎮",
    area: "雷斯湖",
    island: "南島",
    tier: "一星",
    cuisine: "創新料理（官方分類：Innovative，野生／採集食材為主）",
    chef: "Vaughan Mabee",
    priceNT: 7210,
    priceDisplay: "午餐套餐 NZ$395／人；晚餐12道式 NZ$440／人；至尊套餐 NZ$595／人",
    priceVerified: true,
    within: false,
    reservation: "線上Tock系統／email；2026年查詢時餐廳曾因整修暫時休業",
    gmaps: "https://www.google.com/maps/search/?api=1&query=10%20Arrowtown-Lake%20Hayes%20Road%2C%20Queenstown%2C%209371",
    address: "10 Arrowtown-Lake Hayes Road, Queenstown, 9371",
    signature: "野生黇鹿；莊園自產黑皮諾",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/amisfield",
  },
  {
    id: "r008",
    name: "Rātā",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，中奧塔哥食材）",
    chef: "Josh Emett ＆ Fleur Caulton（主廚 Dan Matto）",
    priceNT: 1640,
    priceDisplay: "單點主菜 NZ$44–140／人（適量點餐可控制預算）",
    priceVerified: true,
    within: true,
    reservation: "官方網站；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Te%20Nuku%2C%2043%20Ballarat%20Street%2C%20Queenstown%2C%209348",
    address: "Te Nuku, 43 Ballarat Street, Queenstown, 9348",
    signature: null,
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/rata",
  },
  {
    id: "r009",
    name: "Sherwood",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，約九成食材自種／採集）",
    chef: "Chris Scott",
    priceNT: 1820,
    priceDisplay: "柴燒烤餅 NZ$12–30；3道式套餐 NZ$100／人",
    priceVerified: true,
    within: true,
    reservation: "餐廳官網直接聯繫；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=554%20Frankton%20Road%2C%20Queenstown%2C%209300",
    address: "554 Frankton Road, Queenstown, 9300",
    signature: "竹莢魚生食；柴燒烤餅",
    source: "guide.michelin.com/en/south-island/queenstown_2306160/restaurant/sherwood",
  },
  {
    id: "r010",
    name: "Kika",
    city: "皇后鎮",
    area: "瓦納卡",
    island: "南島",
    tier: "一星",
    cuisine: "現代紐西蘭＋義式風味分享菜（官方英文分類未查證）",
    chef: "James Stapley",
    priceNT: 1820,
    priceDisplay: "「別問就吃」／「信任主廚」套餐約 NZ$100／人（含酒水搭配）",
    priceVerified: true,
    within: true,
    reservation: "官方網站線上訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Kika%20%E7%93%A6%E7%B4%8D%E5%8D%A1%20New%20Zealand%20restaurant",
    address: null,
    signature: "生牛肉塔塔佐溏心蛋；歐哈湖和牛牛小排",
    source: "未取得米其林官方Kika頁面核對結果",
  },
  {
    id: "r011",
    name: "Inati",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "歐陸當代料理（官方分類：European Contemporary）",
    chef: "Simon ＆ Lisa Levy",
    priceNT: 2740,
    priceDisplay: "「信任我們」6道式 NZ$129／人；8道式 NZ$165／人（另有含酒款套餐）",
    priceVerified: true,
    within: true,
    reservation: "官方網站／電話 +64 3-390 1580",
    gmaps: "https://www.google.com/maps/search/?api=1&query=48%20Hereford%20Street%2C%20Christchurch%20Central%20City%2C%20Christchurch%2C%208013",
    address: "48 Hereford Street, Christchurch Central City, Christchurch, 8013",
    signature: "「牛肉甜甜圈」（燉牛頰內餡）；14天熟成杜克香料鴨",
    source: "guide.michelin.com/en/south-island/christchurch_2307083/restaurant/inati",
  },
  {
    id: "r012",
    name: "Tussock Hill",
    city: "基督城",
    area: "卡什米爾",
    island: "南島",
    tier: "一星",
    cuisine: "紐西蘭料理（官方分類：New Zealand，僅供午餐時令分享菜）",
    chef: "Adam Harrison（官方頁面標示聲明人，原始資料未載主廚姓名）",
    priceNT: 1640,
    priceDisplay: "「精選午餐」NZ$90／人",
    priceVerified: true,
    within: true,
    reservation: "官方網站（僅供午餐）；餐廳自行管理訂位",
    gmaps: "https://www.google.com/maps/search/?api=1&query=210%20Huntsbury%20Avenue%2C%20Cashmere%2C%20Christchurch%2C%208022",
    address: "210 Huntsbury Avenue, Cashmere, Christchurch, 8022",
    signature: null,
    source: "guide.michelin.com/en/south-island/christchurch_2307083/restaurant/tussock-hill",
  },
  {
    id: "r013",
    name: "Apéro Food ＆ Wine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "K'Road一帶葡萄酒吧小盤料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ap%C3%A9ro%20Food%20%EF%BC%86%20Wine%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r014",
    name: "Atelier",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式風格小酒館",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Atelier%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r015",
    name: "Bianca",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bianca%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r016",
    name: "Bistro Saine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式小酒館",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bistro%20Saine%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r017",
    name: "Boda",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "泰式料理（原始資料標示；Wikipedia列為韓式，兩來源分類不一致，未查證何者為準）",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Boda%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r018",
    name: "Cazador",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "蒙特伊登，野味／波斯／地中海料理",
    chef: "未查證",
    priceNT: 1810,
    priceDisplay: "NZ$99／人套餐（Cazador「盛宴」）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Cazador%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r019",
    name: "Gemmayze Street",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "K'Road，黎巴嫩料理",
    chef: "未查證",
    priceNT: 1370,
    priceDisplay: "主餐 NZ$40，套餐 NZ$65–110",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Gemmayze%20Street%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r020",
    name: "Goat",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "小盤料理與葡萄酒",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Goat%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r021",
    name: "Milenta",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "哥倫比亞料理（Wikipedia標示；原始資料標示「當代料理」，取Wikipedia較具體分類）",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Milenta%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r022",
    name: "Osteria Uno",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Osteria%20Uno%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r023",
    name: "Parro",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "西班牙料理（Wikipedia標示；原始資料標示「當代料理」）",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Parro%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r024",
    name: "Pasta ＆ Cuore",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式手工麵食",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Pasta%20%EF%BC%86%20Cuore%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r025",
    name: "Tempero",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "巴西料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Tempero%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r026",
    name: "A'mano",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "義式料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=A%27mano%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r027",
    name: "Earl",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "歐式料理（Wikipedia標示：European；原始資料標示「當代小酒館」）",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Earl%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r028",
    name: "Fire and Slice",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "披薩／小酒館",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Fire%20and%20Slice%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r029",
    name: "Gatherings",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "梅里維爾，時令有機料理，僅20席",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Gatherings%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r030",
    name: "Londo",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "梅里維爾，迷你葡萄酒吧（僅3桌＋吧台）",
    chef: "Robert Fairs（官方確認為2026年MICHELIN Young Chef Award得主）",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Londo%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r031",
    name: "Odeon",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "安達魯西亞／地中海分享菜，柴燒烹調",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Odeon%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r032",
    name: "Roca",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "地中海／西班牙風味，柴燒烹調",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Roca%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r033",
    name: "Soul Quarter",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "南方料理（Southern，Wikipedia標示）",
    chef: "未查證",
    priceNT: 820,
    priceDisplay: "巨無霸明蝦約NZ$3／隻；炭烤羊肉盤約NZ$45",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Soul%20Quarter%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r034",
    name: "The Athens Yacht Club",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "希臘料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Athens%20Yacht%20Club%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r035",
    name: "The Monday Room",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "歐陸家庭式分享盛宴",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Monday%20Room%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r036",
    name: "Aosta",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "箭鎮，義式料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Aosta%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r037",
    name: "Bombay Palace",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，印度料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bombay%20Palace%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r038",
    name: "Francesca",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，義式料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Francesca%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r039",
    name: "Muttonbird",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，當代紐西蘭料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Muttonbird%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r040",
    name: "Paloma Taqueria",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，墨西哥塔可",
    chef: "未查證",
    priceNT: 820,
    priceDisplay: "任選套餐約NZ$49／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Paloma%20Taqueria%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r041",
    name: "Sundays",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "皇后鎮，當代料理",
    chef: "未查證",
    priceNT: 820,
    priceDisplay: "柴燒披薩NZ$30–34、經典起司義大利麵NZ$27",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Sundays%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r042",
    name: "The Cow",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "皇后鎮，披薩與起司鍋",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Cow%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r043",
    name: "Treehouse",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（必比登官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Treehouse%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r044",
    name: "The French Café",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "法式／歐陸料理",
    chef: "Sid Sahrawat",
    priceNT: 2830,
    priceDisplay: "食物套餐 NZ$155–190／人（不含酒款）；含酒款可達NZ$305",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=210%20Symonds%20Street%2C%20Eden%20Terrace%2C%20Auckland%2C%201011",
    address: "210 Symonds Street, Eden Terrace, Auckland, 1011",
    signature: "紐西蘭2026米其林侍酒師大獎得主餐廳（主理人Matthew Aitchison）；主廚Sid與Chand Sahrawat",
    source: null,
  },
  {
    id: "r045",
    name: "Onslow",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代紐西蘭料理",
    chef: "Josh Emett",
    priceNT: 1280,
    priceDisplay: "單點／套餐（價位隨菜色變動）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Onslow%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r046",
    name: "Cassia",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代印度料理",
    chef: "Sid ＆ Chand Sahrawat",
    priceNT: 1820,
    priceDisplay: "蔬食套餐 NZ$175／人；單點約NZ$100／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Cassia%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "2026年搬遷至市中心新址",
    source: null,
  },
  {
    id: "r047",
    name: "Metita",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "太平洋／玻里尼西亞料理",
    chef: "Michael Meredith",
    priceNT: 640,
    priceDisplay: "單點主菜 NZ$30–40",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Metita%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r048",
    name: "Kol",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "印度風味柴燒料理",
    chef: "Sahrawat家族",
    priceNT: 730,
    priceDisplay: "單點 NZ$20–42；主廚精選套餐約NZ$95",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Kol%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r049",
    name: "Origine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代法式／紐西蘭小酒館",
    chef: "Ben Bayly",
    priceNT: 910,
    priceDisplay: "單點 NZ$40–60；套餐約NZ$49",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Origine%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r050",
    name: "Mr Morris",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代太平洋／紐西蘭料理",
    chef: "Michael Meredith",
    priceNT: 2280,
    priceDisplay: "套餐約NZ$125／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Mr%20Morris%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r051",
    name: "Kingi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "永續海鮮料理",
    chef: "Tom Hishon",
    priceNT: 770,
    priceDisplay: "單點主菜 NZ$38–46",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Kingi%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r052",
    name: "Ki Māha",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "懷希基島，紐西蘭／國際料理",
    chef: "Vicky Shah",
    priceNT: 1280,
    priceDisplay: "單點＋3道式套餐",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ki%20M%C4%81ha%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r053",
    name: "Gilt（Gilt Brasserie）",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸小酒館",
    chef: "Josh ＆ Helen Emett",
    priceNT: 770,
    priceDisplay: "單點主菜 NZ$38–46",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Gilt%EF%BC%88Gilt%20Brasserie%EF%BC%89%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r054",
    name: "Esther",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "地中海料理",
    chef: "Sean Connolly",
    priceNT: 1130,
    priceDisplay: "戲前2道式 NZ$59；套餐約NZ$65",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Esther%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r055",
    name: "Baduzzi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式料理",
    chef: "Michael Dearth",
    priceNT: 380,
    priceDisplay: "單盤 NZ$14–28",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Baduzzi%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r056",
    name: "Jervois Steak House",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "牛排館（高級部位可能超出預算）",
    chef: "未查證",
    priceNT: 1190,
    priceDisplay: "工作日午餐套餐NZ$65；單點牛排視部位而定，高級切割可能超出NT$5,000",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Jervois%20Steak%20House%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "皇后鎮亦有分店",
    source: null,
  },
  {
    id: "r057",
    name: "Sails",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "海鮮／精緻料理",
    chef: "未查證",
    priceNT: 880,
    priceDisplay: "單點主菜 NZ$36–59；另有品嚐套餐",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Sails%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "碼頭景觀，品嚐套餐可能接近預算上限",
    source: null,
  },
  {
    id: "r058",
    name: "Otto",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式料理",
    chef: "未查證",
    priceNT: 510,
    priceDisplay: "單點多在NZ$28以內",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Otto%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r059",
    name: "Lillius",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸料理",
    chef: "Fraser McCarthy",
    priceNT: 1280,
    priceDisplay: "3道式套餐 NZ$70／人；另有5／8道式品嚐套餐",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Lillius%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r060",
    name: "Ada",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "原生食材紐西蘭小酒館",
    chef: "Kia Kanuta",
    priceNT: 1620,
    priceDisplay: "「餵飽我」套餐 NZ$89／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ada%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r061",
    name: "Advieh",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "中東／波斯料理",
    chef: "Gareth Stewart",
    priceNT: 1950,
    priceDisplay: "宴席套餐 NZ$89或NZ$125／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Advieh%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r062",
    name: "Alma",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "西班牙安達魯西亞料理",
    chef: "未查證",
    priceNT: 1730,
    priceDisplay: "團體套餐 NZ$95／人；單點NZ$6–120（龍蝦類單點可能超出預算）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Alma%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r063",
    name: "Bar Magda",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代菲律賓料理",
    chef: "Carlo Buenaventura",
    priceNT: 1390,
    priceDisplay: "宴席套餐 NZ$65或NZ$88／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bar%20Magda%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r064",
    name: "Bossi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式料理",
    chef: "Shaun Dowling",
    priceNT: 600,
    priceDisplay: "單點主菜 NZ$26–40",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bossi%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r065",
    name: "East",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代亞洲蔬食料理",
    chef: "未查證",
    priceNT: 1550,
    priceDisplay: "「信任主廚」套餐 NZ$85／人",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=East%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r066",
    name: "Hello Beasty",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "亞洲融合料理",
    chef: "未查證",
    priceNT: 510,
    priceDisplay: "分享菜 NZ$14–42",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Hello%20Beasty%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r067",
    name: "Morell",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代小酒館",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Morell%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r068",
    name: "One Tree Grill",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸／牛排料理",
    chef: "未查證",
    priceNT: 1060,
    priceDisplay: "單點主菜 NZ$27–58；6道式品嚐套餐可能超出預算",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=One%20Tree%20Grill%20%20New%20Zealand%20restaurant",
    address: null,
    signature: "奧克蘭老字號名店",
    source: null,
  },
  {
    id: "r069",
    name: "Ragtag",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "國際融合料理",
    chef: "Dan Freeman",
    priceNT: 910,
    priceDisplay: "中價位融合菜色",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Ragtag%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r070",
    name: "Rodd ＆ Gunn The Lodge",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代紐西蘭小酒館",
    chef: "Matt Lambert",
    priceNT: 820,
    priceDisplay: "前菜 NZ$15–29；主菜 NZ$25–45（牛排單點可達NZ$85）",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Rodd%20%EF%BC%86%20Gunn%20The%20Lodge%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r071",
    name: "1947 Eatery",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代印度料理",
    chef: "Jaspal Singh",
    priceNT: 860,
    priceDisplay: "單點主菜 NZ$29–47",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=1947%20Eatery%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r072",
    name: "Bessie",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bessie%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r073",
    name: "Cellar Door",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Cellar%20Door%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r074",
    name: "Hugo",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Hugo%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r075",
    name: "Miro",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Miro%20%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r076",
    name: "Arc",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Arc%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r077",
    name: "Bianca by Giovi",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "義式料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Bianca%20by%20Giovi%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r078",
    name: "Billy's",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Billy%27s%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r079",
    name: "Botswana Butchery",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "高級肉類料理",
    chef: "未查證",
    priceNT: 1460,
    priceDisplay: "精緻肉類料理，高級部位可能超出NT$5,000",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Botswana%20Butchery%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r080",
    name: "Jervois Steak House",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "牛排館（皇后鎮分店）",
    chef: "未查證",
    priceNT: 1190,
    priceDisplay: "高級牛排單點可能超出預算",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Jervois%20Steak%20House%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r081",
    name: "Millhouse",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Millhouse%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r082",
    name: "Nest",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "湖景當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Nest%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r083",
    name: "Rodd ＆ Gunn The Lodge",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "現代紐西蘭小酒館（皇后鎮分店）",
    chef: "未查證",
    priceNT: 820,
    priceDisplay: "與奧克蘭分店價位相近",
    priceVerified: true,
    within: true,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Rodd%20%EF%BC%86%20Gunn%20The%20Lodge%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r084",
    name: "Soda",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Soda%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r085",
    name: "The Dining Room",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "精緻餐飲（Eichardt's酒店）",
    chef: "未查證",
    priceNT: 1640,
    priceDisplay: "精緻套餐，可能接近或超出預算上限",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Dining%20Room%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r086",
    name: "The Woolshed",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=The%20Woolshed%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r087",
    name: "Toast ＆ Oak",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "葡萄酒吧／小酒館",
    chef: "未查證",
    priceNT: null,
    priceDisplay: "未查證（官方頁面未列個別價位）",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=Toast%20%EF%BC%86%20Oak%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
  {
    id: "r088",
    name: "True South Dining Room",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "湖景精緻餐飲（The Rees酒店）",
    chef: "未查證",
    priceNT: 1640,
    priceDisplay: "精緻套餐，可能接近或超出預算上限",
    priceVerified: false,
    within: null,
    reservation: "未查證（需洽官網／電話確認）",
    gmaps: "https://www.google.com/maps/search/?api=1&query=True%20South%20Dining%20Room%20%E5%90%AB%E7%93%A6%E7%B4%8D%E5%8D%A1%EF%BC%8F%E7%AE%AD%E9%8E%AE%20New%20Zealand%20restaurant",
    address: null,
    signature: null,
    source: null,
  },
];
