const RESTAURANTS = [
  {
    id: "r001",
    name: "Essence",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "二星",
    cuisine: "當代紐西蘭／歐陸技法",
    priceNT: 5380,
    priceDisplay: "NZ$295–450／人（品嚐套餐）",
    within: false,
    reservation: "官方網站／電話",
    leadTime: "得獎後訂位緊張，聖誕節前釋出座位有限",
    signature: "生蠔、克雷鎮龍蝦、鴨肉、榲桲；侍酒師精選黑皮諾酒單",
    chef: "Paul Froggatt（ROKI Collection 主廚總監）",
    status: "全紐唯一二星，新入選",
  },
  {
    id: "r002",
    name: "Ahi.",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "當代紐西蘭（柴燒料理）",
    priceNT: 1620,
    priceDisplay: "三道式午／晚餐 NZ$89起；另有長套餐",
    within: true,
    reservation: "官方網站，可現場候位",
    leadTime: "建議提前2–4週",
    signature: "卡瓦卡瓦酸種佐自製發酵奶油；帝馬圖庫生蠔、螯蝦",
    chef: "Ben Bayly",
    status: "新入榜；主廚自營南奧克蘭菜園",
  },
  {
    id: "r003",
    name: "Paris Butter",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "法式技法融合紐西蘭食材與亞洲調味",
    priceNT: 3010,
    priceDisplay: "季節套餐 NZ$145–185／人；侍酒搭配 +NZ$75–110",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Nick Honeyman ＆ Zennon Wijlens",
    status: "新入榜（Cuisine雜誌三頂主廚帽）",
  },
  {
    id: "r004",
    name: "Tala",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "當代薩摩亞料理（全球首個薩摩亞料理米其林星）",
    priceNT: 3470,
    priceDisplay: "「主廚之旅」14道 NZ$215／人；「故事之旅」NZ$165／人",
    within: true,
    reservation: "官方網站／電話，分三個場次",
    leadTime: "得獎後主廚旅程套餐約需提前4週",
    signature: "土窯烤春雞、椰漿麵包、太平洋海棗",
    chef: "Henry ＆ Debby Onesemo",
    status: "新入榜",
  },
  {
    id: "r005",
    name: "Mudbrick",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "歐陸／日式／印度風味融合，酒莊穀倉餐廳",
    priceNT: 3190,
    priceDisplay: "5道式套餐 NZ$175／人；另有3道式",
    within: true,
    reservation: "官方網站，用餐前24小時內須確認",
    leadTime: "餐廳整修中，8月14日重新開放（期間可用Archive Bistro）",
    signature: "帝馬庫圖生蠔；琴通寧風味甜點",
    chef: "Mrinal Ghosal",
    status: "新入榜",
  },
  {
    id: "r006",
    name: "The Estate（Tantalus Estate）",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "一星",
    cuisine: "法式技法結合紐西蘭產地食材，酒莊餐廳",
    priceNT: 3190,
    priceDisplay: "「信任主廚」5道式 NZ$175／人；另有3道式",
    within: true,
    reservation: "官方網站，務必訂位",
    leadTime: "午餐週三至週日；晚餐限週六",
    signature: "",
    chef: "Axel Curtet-Latreille",
    status: "新入榜",
  },
  {
    id: "r007",
    name: "Amisfield",
    city: "皇后鎮",
    area: "雷斯湖",
    island: "南島",
    tier: "一星",
    cuisine: "中奧塔哥產地食材，野生／採集食材為主",
    priceNT: 7210,
    priceDisplay: "午餐套餐 NZ$395／人；晚餐12道式 NZ$440／人；至尊套餐 NZ$595／人",
    within: false,
    reservation: "線上Tock系統／email",
    leadTime: "餐廳曾於5–7月整修休業，現已重新開放",
    signature: "野生黇鹿；莊園自產黑皮諾",
    chef: "Vaughan Mabee",
    status: "新入榜",
  },
  {
    id: "r008",
    name: "Rātā",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "當代紐西蘭料理，中奧塔哥食材",
    priceNT: 1640,
    priceDisplay: "單點主菜 NZ$44–140／人（適量點餐可控制預算）",
    within: true,
    reservation: "官方網站",
    leadTime: "得獎當晚起即可訂位",
    signature: "",
    chef: "Josh Emett ＆ Fleur Caulton（主廚 Dan Matto）",
    status: "新入榜",
  },
  {
    id: "r009",
    name: "Sherwood",
    city: "皇后鎮",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "自家菜園產地到餐桌，約九成食材自種／採集",
    priceNT: 1820,
    priceDisplay: "柴燒烤餅 NZ$12–30；3道式套餐 NZ$100／人",
    within: true,
    reservation: "餐廳官網直接聯繫",
    leadTime: "得獎當晚起即可訂位",
    signature: "竹莢魚生食；柴燒烤餅",
    chef: "主廚 Chris",
    status: "新入榜",
  },
  {
    id: "r010",
    name: "Kika",
    city: "皇后鎮",
    area: "瓦納卡",
    island: "南島",
    tier: "一星",
    cuisine: "現代紐西蘭＋義式風味分享菜",
    priceNT: 1820,
    priceDisplay: "「別問就吃」／「信任主廚」套餐約 NZ$100／人（含酒水搭配）",
    within: true,
    reservation: "官方網站線上訂位",
    leadTime: "確認時間為前一天",
    signature: "生牛肉塔塔佐溏心蛋；歐哈湖和牛牛小排",
    chef: "James Stapley",
    status: "新入榜",
  },
  {
    id: "r011",
    name: "Inati",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "一星",
    cuisine: "分享式重新演繹歐陸經典料理，坎特伯里在地食材",
    priceNT: 2740,
    priceDisplay: "「信任我們」6道式 NZ$129／人；8道式 NZ$165／人（另有含酒款套餐）",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "得獎當晚起即可訂位",
    signature: "「牛肉甜甜圈」（燉牛頰內餡）；14天熟成杜克香料鴨",
    chef: "Simon ＆ Lisa Levy",
    status: "新入榜",
  },
  {
    id: "r012",
    name: "Tussock Hill",
    city: "基督城",
    area: "卡什米爾",
    island: "南島",
    tier: "一星",
    cuisine: "僅供午餐，時令分享菜搭配莊園有機酒款",
    priceNT: 1640,
    priceDisplay: "「精選午餐」NZ$90／人",
    within: true,
    reservation: "官方網站（僅供午餐）",
    leadTime: "得獎當晚湧入153筆訂位，全年訂位緊俏",
    signature: "",
    chef: "",
    status: "新入榜",
  },
  {
    id: "r013",
    name: "Apéro Food ＆ Wine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "K'Road一帶葡萄酒吧小盤料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r014",
    name: "Atelier",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式風格小酒館",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r015",
    name: "Bianca",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r016",
    name: "Bistro Saine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "法式小酒館",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r017",
    name: "Boda",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "泰式料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r018",
    name: "Cazador",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "蒙特伊登，野味／波斯／地中海料理",
    priceNT: 1810,
    priceDisplay: "NZ$99／人套餐（Cazador「盛宴」）",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r019",
    name: "Gemmayze Street",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "K'Road，黎巴嫩料理",
    priceNT: 1370,
    priceDisplay: "主餐 NZ$40，套餐 NZ$65–110",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r020",
    name: "Goat",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "小盤料理與葡萄酒",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r021",
    name: "Milenta",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "當代料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r022",
    name: "Osteria Uno",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r023",
    name: "Parro",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "當代料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r024",
    name: "Pasta ＆ Cuore",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "義式手工麵食",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r025",
    name: "Tempero",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "必比登",
    cuisine: "巴西料理",
    priceNT: 910,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r026",
    name: "A'mano",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "義式料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r027",
    name: "Earl",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "當代小酒館",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r028",
    name: "Fire and Slice",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "披薩／小酒館",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r029",
    name: "Gatherings",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "梅里維爾，時令有機料理，僅20席",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r030",
    name: "Londo",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "梅里維爾，迷你葡萄酒吧（僅3桌＋吧台）",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r031",
    name: "Odeon",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "安達魯西亞／地中海分享菜，柴燒烹調",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r032",
    name: "Roca",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "地中海／西班牙風味，柴燒烹調",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r033",
    name: "Soul Quarter",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "巨無霸明蝦、炭烤坎特伯里羊肉",
    priceNT: 820,
    priceDisplay: "巨無霸明蝦約NZ$3／隻；炭烤羊肉盤約NZ$45",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r034",
    name: "The Athens Yacht Club",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "希臘料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r035",
    name: "The Monday Room",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "必比登",
    cuisine: "歐陸家庭式分享盛宴",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r036",
    name: "Aosta",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "箭鎮，義式料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r037",
    name: "Bombay Palace",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，印度料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r038",
    name: "Francesca",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，義式料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r039",
    name: "Muttonbird",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，當代紐西蘭料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r040",
    name: "Paloma Taqueria",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，墨西哥塔可",
    priceNT: 820,
    priceDisplay: "任選套餐約NZ$49／人",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r041",
    name: "Sundays",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "皇后鎮，當代料理",
    priceNT: 820,
    priceDisplay: "柴燒披薩NZ$30–34、經典起司義大利麵NZ$27",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r042",
    name: "The Cow",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "皇后鎮，披薩與起司鍋",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r043",
    name: "Treehouse",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "必比登",
    cuisine: "瓦納卡，當代料理",
    priceNT: 820,
    priceDisplay: "必比登認證，高CP值套餐／單點",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "必比登（高CP值優選）",
  },
  {
    id: "r044",
    name: "The French Café",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "法式／歐陸料理",
    priceNT: 2830,
    priceDisplay: "食物套餐 NZ$155–190／人（不含酒款）；含酒款可達NZ$305",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "紐西蘭2026侍酒師大獎得主餐廳",
    chef: "Sid Sahrawat",
    status: "MICHELIN精選",
  },
  {
    id: "r045",
    name: "Onslow",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代紐西蘭料理",
    priceNT: 1280,
    priceDisplay: "單點／套餐（價位隨菜色變動）",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Josh Emett",
    status: "MICHELIN精選",
  },
  {
    id: "r046",
    name: "Cassia",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代印度料理",
    priceNT: 1820,
    priceDisplay: "蔬食套餐 NZ$175／人；單點約NZ$100／人",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "2026年搬遷至市中心新址",
    chef: "Sid ＆ Chand Sahrawat",
    status: "MICHELIN精選",
  },
  {
    id: "r047",
    name: "Metita",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "太平洋／玻里尼西亞料理",
    priceNT: 640,
    priceDisplay: "單點主菜 NZ$30–40",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Michael Meredith",
    status: "MICHELIN精選",
  },
  {
    id: "r048",
    name: "Kol",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "印度風味柴燒料理",
    priceNT: 730,
    priceDisplay: "單點 NZ$20–42；主廚精選套餐約NZ$95",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Sahrawat家族",
    status: "MICHELIN精選",
  },
  {
    id: "r049",
    name: "Origine",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代法式／紐西蘭小酒館",
    priceNT: 910,
    priceDisplay: "單點 NZ$40–60；套餐約NZ$49",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Ben Bayly",
    status: "MICHELIN精選",
  },
  {
    id: "r050",
    name: "Mr Morris",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代太平洋／紐西蘭料理",
    priceNT: 2280,
    priceDisplay: "套餐約NZ$125／人",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Michael Meredith",
    status: "MICHELIN精選",
  },
  {
    id: "r051",
    name: "Kingi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "永續海鮮料理",
    priceNT: 770,
    priceDisplay: "單點主菜 NZ$38–46",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Tom Hishon",
    status: "MICHELIN精選",
  },
  {
    id: "r052",
    name: "Ki Māha",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "懷希基島，紐西蘭／國際料理",
    priceNT: 1280,
    priceDisplay: "單點＋3道式套餐",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Vicky Shah",
    status: "MICHELIN精選",
  },
  {
    id: "r053",
    name: "Gilt（Gilt Brasserie）",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸小酒館",
    priceNT: 770,
    priceDisplay: "單點主菜 NZ$38–46",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Josh ＆ Helen Emett",
    status: "MICHELIN精選",
  },
  {
    id: "r054",
    name: "Esther",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "地中海料理",
    priceNT: 1130,
    priceDisplay: "戲前2道式 NZ$59；套餐約NZ$65",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Sean Connolly",
    status: "MICHELIN精選",
  },
  {
    id: "r055",
    name: "Baduzzi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式料理",
    priceNT: 380,
    priceDisplay: "單盤 NZ$14–28",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Michael Dearth",
    status: "MICHELIN精選",
  },
  {
    id: "r056",
    name: "Jervois Steak House",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "牛排館（高級部位可能超出預算）",
    priceNT: 1190,
    priceDisplay: "工作日午餐套餐NZ$65；單點牛排視部位而定，高級切割可能超出NT$5,000",
    within: false,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "皇后鎮亦有分店",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r057",
    name: "Sails",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "海鮮／精緻料理",
    priceNT: 880,
    priceDisplay: "單點主菜 NZ$36–59；另有品嚐套餐",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "碼頭景觀，品嚐套餐可能接近預算上限",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r058",
    name: "Otto",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式料理",
    priceNT: 510,
    priceDisplay: "單點多在NZ$28以內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r059",
    name: "Lillius",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸料理",
    priceNT: 1280,
    priceDisplay: "3道式套餐 NZ$70／人；另有5／8道式品嚐套餐",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Fraser McCarthy",
    status: "MICHELIN精選",
  },
  {
    id: "r060",
    name: "Ada",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "原生食材紐西蘭小酒館",
    priceNT: 1620,
    priceDisplay: "「餵飽我」套餐 NZ$89／人",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Kia Kanuta",
    status: "MICHELIN精選",
  },
  {
    id: "r061",
    name: "Advieh",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "中東／波斯料理",
    priceNT: 1950,
    priceDisplay: "宴席套餐 NZ$89或NZ$125／人",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Gareth Stewart",
    status: "MICHELIN精選",
  },
  {
    id: "r062",
    name: "Alma",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "西班牙安達魯西亞料理",
    priceNT: 1730,
    priceDisplay: "團體套餐 NZ$95／人；單點NZ$6–120（龍蝦類單點可能超出預算）",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r063",
    name: "Bar Magda",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代菲律賓料理",
    priceNT: 1390,
    priceDisplay: "宴席套餐 NZ$65或NZ$88／人",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Carlo Buenaventura",
    status: "MICHELIN精選",
  },
  {
    id: "r064",
    name: "Bossi",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "義式料理",
    priceNT: 600,
    priceDisplay: "單點主菜 NZ$26–40",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Shaun Dowling",
    status: "MICHELIN精選",
  },
  {
    id: "r065",
    name: "East",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代亞洲蔬食料理",
    priceNT: 1550,
    priceDisplay: "「信任主廚」套餐 NZ$85／人",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r066",
    name: "Hello Beasty",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "亞洲融合料理",
    priceNT: 510,
    priceDisplay: "分享菜 NZ$14–42",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r067",
    name: "Morell",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代小酒館",
    priceNT: null,
    priceDisplay: "價位未公開，估計在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r068",
    name: "One Tree Grill",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "歐陸／牛排料理",
    priceNT: 1060,
    priceDisplay: "單點主菜 NZ$27–58；6道式品嚐套餐可能超出預算",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "奧克蘭老字號名店",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r069",
    name: "Ragtag",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "國際融合料理",
    priceNT: 910,
    priceDisplay: "中價位融合菜色",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Dan Freeman",
    status: "MICHELIN精選",
  },
  {
    id: "r070",
    name: "Rodd ＆ Gunn The Lodge",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "現代紐西蘭小酒館",
    priceNT: 820,
    priceDisplay: "前菜 NZ$15–29；主菜 NZ$25–45（牛排單點可達NZ$85）",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Matt Lambert",
    status: "MICHELIN精選",
  },
  {
    id: "r071",
    name: "1947 Eatery",
    city: "奧克蘭",
    area: "",
    island: "北島",
    tier: "精選",
    cuisine: "當代印度料理",
    priceNT: 860,
    priceDisplay: "單點主菜 NZ$29–47",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "Jaspal Singh",
    status: "MICHELIN精選",
  },
  {
    id: "r072",
    name: "Bessie",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r073",
    name: "Cellar Door",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r074",
    name: "Hugo",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r075",
    name: "Miro",
    city: "基督城",
    area: "",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "洽詢餐廳／官網訂位",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r076",
    name: "Arc",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r077",
    name: "Bianca by Giovi",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "義式料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r078",
    name: "Billy's",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r079",
    name: "Botswana Butchery",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "高級肉類料理",
    priceNT: 1460,
    priceDisplay: "精緻肉類料理，高級部位可能超出NT$5,000",
    within: false,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r080",
    name: "Jervois Steak House",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "牛排館（皇后鎮分店）",
    priceNT: 1190,
    priceDisplay: "高級牛排單點可能超出預算",
    within: false,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r081",
    name: "Millhouse",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r082",
    name: "Nest",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "湖景當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內（湖景座位可能加價）",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r083",
    name: "Rodd ＆ Gunn The Lodge",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "現代紐西蘭小酒館（皇后鎮分店）",
    priceNT: 820,
    priceDisplay: "與奧克蘭分店價位相近",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r084",
    name: "Soda",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r085",
    name: "The Dining Room",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "精緻餐飲（Eichardt's酒店）",
    priceNT: 1640,
    priceDisplay: "精緻套餐，可能接近或超出預算上限",
    within: false,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r086",
    name: "The Woolshed",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "當代料理",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r087",
    name: "Toast ＆ Oak",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "葡萄酒吧／小酒館",
    priceNT: null,
    priceDisplay: "價位未公開，預期落在預算內",
    within: true,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
  {
    id: "r088",
    name: "True South Dining Room",
    city: "皇后鎮",
    area: "含瓦納卡／箭鎮",
    island: "南島",
    tier: "精選",
    cuisine: "湖景精緻餐飲（The Rees酒店）",
    priceNT: 1640,
    priceDisplay: "精緻套餐，可能接近或超出預算上限",
    within: false,
    reservation: "官方網站／電話",
    leadTime: "",
    signature: "",
    chef: "",
    status: "MICHELIN精選",
  },
];
